-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.account_brands (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  account_id uuid,
  vendor_id uuid,
  brand_id uuid,
  discount_percentage numeric,
  multiplier numeric,
  payment_terms character varying,
  minimum_order numeric,
  free_shipping_threshold numeric,
  notes text,
  is_active boolean DEFAULT true,
  negotiated_date date,
  expires_date date,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  tariff_tax numeric,
  wholesale_cost numeric,
  vendor_account_number character varying,
  CONSTRAINT account_brands_pkey PRIMARY KEY (id),
  CONSTRAINT account_brands_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT account_brands_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT account_brands_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.account_vendors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  account_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  vendor_account_number character varying,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT account_vendors_pkey PRIMARY KEY (id),
  CONSTRAINT account_vendors_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT account_vendors_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  business_name character varying,
  email character varying NOT NULL UNIQUE,
  phone character varying,
  address text,
  city character varying,
  state character varying,
  zip_code character varying,
  country character varying DEFAULT 'USA'::character varying,
  timezone character varying DEFAULT 'America/New_York'::character varying,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'suspended'::character varying, 'cancelled'::character varying, 'trial'::character varying]::text[])),
  subscription_tier character varying DEFAULT 'basic'::character varying CHECK (subscription_tier::text = ANY (ARRAY['trial'::character varying, 'basic'::character varying, 'professional'::character varying, 'enterprise'::character varying]::text[])),
  subscription_start_date timestamp with time zone,
  subscription_end_date timestamp with time zone,
  trial_ends_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  metadata jsonb DEFAULT '{}'::jsonb,
  user_id uuid,
  avatar_url text,
  full_name character varying,
  notification_preferences jsonb DEFAULT '{"email_orders": true, "email_inventory": true, "email_marketing": false}'::jsonb,
  display_preferences jsonb DEFAULT '{"theme": "light", "language": "en"}'::jsonb,
  onboarding_completed boolean DEFAULT false,
  email_verified boolean DEFAULT false,
  last_login_at timestamp with time zone,
  questionnaire_completed boolean DEFAULT false,
  questionnaire_skipped boolean DEFAULT false,
  questionnaire_last_prompted timestamp with time zone,
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.api_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  account_id uuid,
  vendor_id uuid,
  endpoint character varying,
  method character varying,
  request_data jsonb,
  response_data jsonb,
  status_code integer,
  error_message text,
  duration_ms integer,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT api_logs_pkey PRIMARY KEY (id),
  CONSTRAINT api_logs_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT api_logs_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.brands (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL UNIQUE,
  vendor_id uuid,
  category character varying,
  tier character varying CHECK (tier::text = ANY (ARRAY['luxury'::character varying, 'premium'::character varying, 'standard'::character varying, 'value'::character varying]::text[])),
  is_active boolean DEFAULT true,
  website character varying,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  wholesale_cost numeric,
  msrp numeric,
  map_price numeric,
  price_last_updated timestamp with time zone,
  price_source character varying,
  entry_level_discount numeric DEFAULT 45.00,
  CONSTRAINT brands_pkey PRIMARY KEY (id),
  CONSTRAINT brands_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.bug_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL,
  user_email text,
  title text NOT NULL,
  description text NOT NULL,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'reviewing'::text, 'in-progress'::text, 'resolved'::text, 'closed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  internal_notes text,
  CONSTRAINT bug_reports_pkey PRIMARY KEY (id),
  CONSTRAINT bug_reports_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.demo_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid,
  user_id uuid,
  step_number integer NOT NULL,
  step_name text NOT NULL,
  time_spent_seconds integer,
  completed boolean DEFAULT false,
  skipped boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT demo_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT demo_analytics_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.demo_data(session_id),
  CONSTRAINT demo_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.demo_data (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL UNIQUE,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval),
  is_active boolean DEFAULT true,
  vendor_id text NOT NULL DEFAULT 'demo-modern-optical'::text,
  vendor_name text NOT NULL DEFAULT 'Modern Optical'::text,
  vendor_account_number text NOT NULL DEFAULT 'MO-12345'::text,
  vendor_email text DEFAULT 'orders@modernoptical.com'::text,
  vendor_phone text DEFAULT '(555) 123-4567'::text,
  vendor_rep_name text DEFAULT 'Sarah Johnson'::text,
  vendor_rep_email text DEFAULT 'sarah.johnson@modernoptical.com'::text,
  vendor_rep_phone text DEFAULT '(555) 123-4569'::text,
  order_data jsonb NOT NULL DEFAULT '{"id": "demo-order-1", "status": "pending", "vendor": "Modern Optical", "order_number": "MO-2024-DEMO", "total_pieces": 3, "customer_name": "Downtown Vision Center", "account_number": "MO-12345"}'::jsonb,
  inventory_items jsonb NOT NULL DEFAULT '[{"id": "demo-item-1", "sku": "MOC-001-BLK-52", "size": "52-18-140", "brand": "Modern Optics Collection", "color": "Black", "model": "Metropolitan", "status": "pending", "quantity": 1, "your_cost": 55, "retail_price": 150, "wholesale_cost": 85}, {"id": "demo-item-2", "sku": "MOC-002-TOR-54", "size": "54-16-142", "brand": "Modern Optics Collection", "color": "Tortoise", "model": "Executive", "status": "pending", "quantity": 1, "your_cost": 55, "retail_price": 150, "wholesale_cost": 85}, {"id": "demo-item-3", "sku": "CS-101-BRN-50", "size": "50-19-145", "brand": "Classic Series", "color": "Brown", "model": "Heritage", "status": "pending", "quantity": 1, "your_cost": 45, "retail_price": 120, "wholesale_cost": 65}]'::jsonb,
  brand_pricing jsonb NOT NULL DEFAULT '[{"id": "demo-modern-collection", "msrp": 150, "name": "Modern Optics Collection", "tier": "Premium", "category": "Fashion", "is_active": true, "map_price": 135, "your_cost": 55, "tariff_tax": 3, "wholesale_cost": 85, "discount_percentage": 35.29}, {"id": "demo-classic-series", "msrp": 120, "name": "Classic Series", "tier": "Standard", "category": "Traditional", "is_active": true, "map_price": 110, "your_cost": 45, "tariff_tax": 2, "wholesale_cost": 65, "discount_percentage": 30.77}]'::jsonb,
  step_progress integer DEFAULT 0,
  completed_steps ARRAY DEFAULT ARRAY[]::integer[],
  last_activity_at timestamp with time zone DEFAULT now(),
  CONSTRAINT demo_data_pkey PRIMARY KEY (id),
  CONSTRAINT demo_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.emails (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  account_id uuid NOT NULL,
  vendor_id uuid,
  message_id character varying,
  from_email character varying,
  to_email character varying,
  subject text,
  received_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  raw_data jsonb,
  plain_text text,
  html_text text,
  attachments_count integer DEFAULT 0,
  spam_score numeric,
  spam_status character varying,
  parse_status character varying DEFAULT 'pending'::character varying CHECK (parse_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'parsed'::character varying, 'failed'::character varying, 'ignored'::character varying]::text[])),
  parsed_data jsonb,
  error_message text,
  duplicate_order boolean DEFAULT false,
  duplicate_message text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  confidence numeric DEFAULT 0,
  CONSTRAINT emails_pkey PRIMARY KEY (id),
  CONSTRAINT emails_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT emails_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  account_id uuid NOT NULL,
  vendor_id uuid,
  order_id uuid,
  email_id uuid,
  sku character varying,
  brand character varying,
  model character varying,
  color character varying,
  color_code character varying,
  color_name character varying,
  size character varying,
  full_size character varying,
  temple_length character varying,
  quantity integer DEFAULT 1,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'current'::character varying, 'sold'::character varying, 'archived'::character varying]::text[])),
  upc character varying,
  ean character varying,
  material character varying,
  country_of_origin character varying,
  wholesale_price numeric,
  msrp numeric,
  selling_price numeric,
  api_verified boolean DEFAULT false,
  confidence_score integer,
  validation_reason text,
  in_stock boolean,
  availability character varying,
  received_date date,
  sold_date date,
  returned_date date,
  enriched_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  received boolean,
  CONSTRAINT inventory_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.emails(id),
  CONSTRAINT inventory_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT inventory_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT inventory_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  account_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['return_report_generated'::text, 'return_report_submitted'::text, 'return_report_completed'::text, 'order_received'::text, 'inventory_updated'::text, 'system_alert'::text, 'info'::text])),
  title text NOT NULL CHECK (length(TRIM(BOTH FROM title)) > 0),
  message text NOT NULL CHECK (length(TRIM(BOTH FROM message)) > 0),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  read boolean NOT NULL DEFAULT false,
  action_url text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  read_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  account_id uuid NOT NULL,
  vendor_id uuid,
  email_id uuid,
  order_number character varying NOT NULL,
  reference_number character varying,
  account_number character varying,
  customer_name character varying,
  customer_code character varying,
  customer_phone character varying,
  placed_by character varying,
  order_date date,
  total_pieces integer DEFAULT 0,
  total_amount numeric,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'partial'::character varying, 'confirmed'::character varying, 'shipped'::character varying, 'delivered'::character varying, 'cancelled'::character varying]::text[])),
  tracking_number character varying,
  shipped_date date,
  delivered_date date,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT orders_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT orders_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.emails(id)
);
CREATE TABLE public.practice_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  account_id uuid NOT NULL UNIQUE,
  practice_type character varying,
  practice_specialty character varying,
  years_in_business integer,
  patient_volume_range character varying,
  current_brands jsonb DEFAULT '[]'::jsonb,
  average_frame_price_range character varying,
  primary_goals jsonb DEFAULT '[]'::jsonb,
  completed_at timestamp with time zone,
  is_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT practice_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT practice_profiles_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.return_report_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  return_report_id uuid NOT NULL,
  inventory_id uuid NOT NULL,
  sku character varying,
  brand character varying,
  model character varying,
  color character varying,
  size character varying,
  quantity integer DEFAULT 1,
  wholesale_price numeric,
  order_date date,
  return_window_expires date,
  reason character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT return_report_items_pkey PRIMARY KEY (id),
  CONSTRAINT return_report_items_return_report_id_fkey FOREIGN KEY (return_report_id) REFERENCES public.return_reports(id),
  CONSTRAINT return_report_items_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.inventory(id)
);
CREATE TABLE public.return_reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  account_id uuid NOT NULL,
  vendor_id uuid,
  report_number character varying NOT NULL UNIQUE,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'generated'::character varying, 'sent'::character varying, 'cancelled'::character varying]::text[])),
  vendor_account_number character varying,
  total_items integer DEFAULT 0,
  total_value numeric DEFAULT 0,
  generated_at timestamp with time zone,
  pdf_path character varying CHECK (pdf_path IS NULL OR pdf_path::text ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/\d{4}/.+\.pdf$'::text),
  sent_to_email character varying,
  sent_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  vendor_name character varying,
  filename character varying,
  item_count integer DEFAULT 0,
  total_quantity integer DEFAULT 0,
  generated_date timestamp with time zone DEFAULT now(),
  CONSTRAINT return_reports_pkey PRIMARY KEY (id),
  CONSTRAINT return_reports_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT return_reports_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.vendor_catalog (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vendor_id uuid NOT NULL,
  vendor_name character varying,
  brand character varying NOT NULL,
  model character varying NOT NULL,
  color character varying,
  color_code character varying,
  sku character varying,
  upc character varying,
  ean character varying,
  wholesale_cost numeric,
  msrp numeric,
  map_price numeric,
  eye_size character varying,
  bridge character varying,
  temple_length character varying,
  full_size character varying,
  material character varying,
  gender character varying,
  fit_type character varying,
  a_measurement character varying,
  b_measurement character varying,
  dbl character varying,
  ed character varying,
  in_stock boolean,
  availability_status character varying,
  confidence_score integer DEFAULT 100,
  data_source character varying CHECK (data_source::text = ANY (ARRAY['web_scrape'::character varying::text, 'api'::character varying::text, 'manual'::character varying::text, 'email_parse'::character varying::text])),
  verified boolean DEFAULT false,
  first_seen_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  last_updated timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  times_ordered integer DEFAULT 1,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT vendor_catalog_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_catalog_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.vendor_reps (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  account_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  rep_name character varying NOT NULL,
  rep_email character varying NOT NULL,
  rep_phone character varying,
  rep_title character varying,
  is_primary boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT vendor_reps_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_reps_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT vendor_reps_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.vendor_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL,
  user_email text,
  vendor_name text NOT NULL,
  vendor_website text,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'reviewing'::text, 'in-progress'::text, 'completed'::text, 'rejected'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  internal_notes text,
  CONSTRAINT vendor_requests_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_requests_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.vendors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL UNIQUE,
  code character varying UNIQUE,
  domain character varying,
  email_patterns jsonb DEFAULT '[]'::jsonb,
  parser_service character varying,
  api_endpoint character varying,
  api_key_encrypted text,
  is_active boolean DEFAULT true,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  contact_email character varying,
  contact_phone character varying,
  CONSTRAINT vendors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.webhook_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  account_id uuid,
  email_id uuid,
  webhook_type character varying,
  payload jsonb,
  processing_status character varying,
  error_message text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT webhook_logs_pkey PRIMARY KEY (id),
  CONSTRAINT webhook_logs_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT webhook_logs_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.emails(id)
);